### ISSUE TITLE
BSC syncing issue

### ISSUE THREAD

**Issue by havsar** [vlddm/binance-smart-chain-node#1]
This is probably not related to this repository itself but still maybe you can help @vlddm.

My node was working fine until like a week or two ago.
Currently, the node syncs until a very recent block without issues but afterwards, it's always behind the newest block and eth_blockNumber returns 0x0.

Can you help in this case? Does the syncing work for you?

Would appreciate any advice!

```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "currentBlock": "0x6c6617",
        "highestBlock": "0x6c6661",
        "knownStates": "0x3644b91",
        "pulledStates": "0x362ec07",
        "startingBlock": "0x6c5ef9"
    }
}
```

**Comment by vlddm** [comment]
https://github.com/ethereum/go-ethereum/issues/16796

**Comment by TobiStr** [comment]
Hallo @vlddm,

I am experiencing the same issue and also the knownStates and pulledStates always remain at 0.
I use Docker on WSL2 with 32GB RAM and i have even moved the docker-data to my NVMe SSD with 1TB.

I think that Docker/WSL might limit the speed too much, so that it will never sync. 
I am trying to install a normal Linux now and give you an update.

________________________________________________________________________________________________________________
Edit:
I set up an ubuntu distribution on my 1TB NVMe SSD and ran the default bsc node.
After around 24h it was synchronized and after an additional 30h, it had built the snapshot (some kind of database for faster access). I think it would be faster to download the current snapshot, before trying to build it yourself.
https://github.com/binance-chain/bsc-snapshots 

So to anyone who is facing synchronizing problems with docker, i would recommend to set up a normal linux distribution.
