### ISSUE TITLE
Unable to locally connect

### ISSUE THREAD

**Issue by BrokedTV** [vlddm/binance-smart-chain-node#3]
Hello there, i really appreciate the docker image, i understand that there is no support over this but i'll try anyway.

I have used the docker image to build a node and it successfully sync, i'm trying to use the node from a local script on the same machine but i'm not able to successfully connect with the indicated port, or what's usually the default port or with the geth.ipc file.

Are there any other commands required to be able to use the node from the same machine others than what's indicated in the readme?

Much appreciated.

**Comment by kozhevnykov** [comment]
@BrokedTV Hi,

Have the same issue, how did you fix it?
Thanks

**Comment by vlddm** [comment]
> Hello there, i really appreciate the docker image, i understand that there is no support over this but i'll try anyway.
> 
> I have used the docker image to build a node and it successfully sync, i'm trying to use the node from a local script on the same machine but i'm not able to successfully connect with the indicated port, or what's usually the default port or with the geth.ipc file.
> 
> Are there any other commands required to be able to use the node from the same machine others than what's indicated in the readme?
> 
> Much appreciated.

Hello there, its fixed in latest version of docker image, please use it.
By default bsc/geth binds http and ws services to 127.0.0.1 so not available outside of docker image.
Ive just fixed it by binding http/ws to 0.0.0.0 in `config.toml`.
So remove old image with `docker image rm vlddm/binance-smart-chain-node:latest` and follow readme.
IPC using `/data/bsc/.ethereum/geth.ipc` should work even in old versions.

**Comment by szhygulin** [comment]
@vlddm Hi,

still, there is an issue with HTTP API. I'd like to send requests from the local machine to the node. But, as you mentioned: 

> By default bsc/geth binds http and ws services to 127.0.0.1 so not available outside of docker image.

However, on ethereum's geth, if I bind port with flag -p 127.0.0.1:8545:8545 I am able to send HTTP request from the local machine to the node. Doing the same thing with your image produces the following result:

`curl: (56) Recv failure: Connection reset by peer`

I guess the problem is that the node thinks that the request came from the outer world. Could you please help with that?
